@startuml
"User" as user_actor

' USECASE
(Просмотр статистики проигрышей и выигрышей) as statlist_usecase
note right of statlist_usecase
  Список игр с отображением характеристик сыгранных игр:
    1. продолжительность игры в минутах
    2. кол-во рейтинга убавилось или уменьшилось
    3. игра была приватная или нет
    4. сколько игроков было в игре
    5. занятое место в игре (первый, второй и тд)
end note
note bottom of statlist_usecase
Например (ключ словаря - айди игры, список - атрибуты сверху):
{
  1: [5, -12, false, 3, 2],
  2: [5, 12, false, 3, 1],
  3: [5, 1, false, 4, 3],
  4: [5, -12, false, 5, 5]
}
end note
' END USECASE

' USECASE
(Присоединиться к игре по ссылке) as join_by_link_to_game_usecase
note bottom of join_by_link_to_game_usecase
У человека, которому доступна ссылка к игре, может открыть ее в браузере и перейти в игру.
Ограничения при присоединении через ссылку:
1) нет мест в лобби
2) если указана опция "только зарегистрированные" и у человека при подключении нет аккаунта (его попросит войти если в браузере из аккаунта вышло), 
то такой пользователь не подключиться к лобби пока не зарегистрируется
3) При опции "только зарегистрированные". Если у пользователя нет рейтинга диапазон который указан в поле "требуемый рейтинг". 
Значение "любой" в этом поле позволяет присоединиться пользователю с любым рейтингом.
end note
' END USECASE

' USECASE
(Просмотр доступных лобби для входа) as list_lobby_usecase
note bottom of list_lobby_usecase
Зарегистрированному пользователю дается список лобби с кнопкой зайти\попросить войти.
Ограничения на отображения лобби другим пользователям:
1. лобби приватное
2. лобби не подходит под выбранный диапазон рейтинга
3. лобби не подходит под выбранные фильтры
end note
' END USECASE

' USECASE
(Общий чат и чат с другом) as chat_all_and_friend_usecase
note bottom of chat_all_and_friend_usecase
Пользователю доступен чат со всеми игроками (как в клэш оф клансе) 
и при просмотре списка друзей есть доступ к чату с другом
end note

' END USECASE

user_actor ---> statlist_usecase
user_actor ---> join_by_link_to_game_usecase
user_actor ---> list_lobby_usecase
user_actor ---> chat_all_and_friend_usecase
@enduml